spring.application.name=ledgermindbackend

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver

telegram.bot-token=${TELEGRAM_BOT_TOKEN}

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash

google.oauth.redirect-uri=${GOOGLE_OAUTH_REDIRECT_URI}
ledgermind.scan.fixed-delay-ms=900000