spring.application.name=ledgermindbackend

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver

app.base-url=${APP_BASE_URL}

google.oauth.client-id=${GOOGLE_CLIENT_ID}
google.oauth.client-secret=${GOOGLE_CLIENT_SECRET}
google.oauth.redirect-uri=${GOOGLE_OAUTH_REDIRECT_URI}

telegram.bot-username=${TELEGRAM_BOT_USERNAME}
telegram.bot-token=${TELEGRAM_BOT_TOKEN}

ai.provider=${AI_PROVIDER}
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash

ledgermind.scan.cron=0 */15 * * * *

telegram.api-url=${TELEGRAM_API_URL}